name: statement
description: Statement package for managing bank statements
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  network:
    path: ../network
  balance:
    path: ../balance
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^9.1.5

