name: bank_statement
description: Bank Statement application with modular architecture
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  core:
    path: ../packages/core
  network:
    path: ../packages/network
  auth:
    path: ../packages/auth
  balance:
    path: ../packages/balance
  statement:
    path: ../packages/statement

  # Routing
  go_router: ^14.0.0

  # Firebase
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.5
  firebase_messaging: ^16.0.4

  # Security
  screen_protector: ^1.3.0

  # State Management
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
